# CI가 끝나야지만 실행되어야 함
name: Development CD workflow

on:
  workflow_run:
    workflows: ['Development CI workflow']
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/haze-api-dev:latest

      - name: Stop Previous Container
        run: |
          if [ "$(docker ps -q -f name=haze-api-dev)" ]; then
            docker stop haze-api-dev
          fi
        continue-on-error: true

      - name: Remove Previous Container
        run: |
          if [ "$(docker ps -q -a -f name=haze-api-dev)" ]; then
            docker rm haze-api-dev
          fi
        continue-on-error: true

      - name: Run Docker Container
        run: docker run -d -p 3001:3001 ${{ secrets.DOCKER_USERNAME }}/haze-api-dev:latest
